### ISSUE TITLE
jmoradi@mozilla.com on build #358: Testing testing. This is Javaun. In Lynchburg Va. Build 358

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#252] opened 2016-11-23 01:40 UTC
Feedback from jmoradi@mozilla.com : Testing testing. This is Javaun. In Lynchburg Va. Build 358

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58345f0c1709f80100415b43/a7fae66b-24be-42d0-b1f2-8f0d1a699a2d.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Nov 23 2016 01:40:30 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>167.5282</td></tr><tr><td>Build</td><td>358</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>iPhone</td></tr><tr><td>Screen size</td><td>320</td></tr><tr><td>Screen size</td><td>320px by 568px</td></tr><tr><td>Battery</td><td>34% Unplugged</td></tr><tr><td>Memory free</td><td>163 MB / 1784 MB</td></tr><tr><td>Disk free</td><td>4506 MB / 56382 MB</td></tr><tr><td>Network IP</td><td>0.0.0.0</td></tr></table>

 [Link to buddybuild feedback from build 358](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5834f38e0fa40a010089316c&bnum=358)

**Comment by fluffyemily** [comment] 2016-11-23 11:32
dupe of #223

**Closed by fluffyemily** 2016-11-23 11:32 UTC
Labels: 1.0, buddybuild-feedback
