### ISSUE TITLE
Force unwrapping nil parameter when tracking card visit to Flurry

### ISSUE THREAD

**Issue by sleroux** [mozilla-mobile/prox#375] opened 2016-11-30 21:05 UTC
Found this while I was trying to track down another crash.

I don't have an actual crash log since this was from Xcode but I'll attach a screenshot below:

![screen shot 2016-11-30 at 4 03 27 pm](https://cloud.githubusercontent.com/assets/434322/20771229/93af6934-b716-11e6-8a68-bace8615cd9b.png)

Looks like we're force-unwrapping a potentially nil value in the `AppState.trackCardVisit` call. I was only able to reproduce by changing my location and returning to the app from the background while swiping through the cards so the underlying assumption that we'll always have a index for our next card view seems to be false.

**Comment by fluffyemily** [comment] 2016-12-01 09:54
Dupe of #353

**Closed by fluffyemily** 2016-12-01 09:54 UTC
Labels: bug
