### ISSUE TITLE
mpopova@mozilla.com on build #358: I had the app in the background.  Then I opened in a new…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#248] opened 2016-11-22 21:41 UTC
Feedback from mpopova@mozilla.com : I had the app in the background.  Then I opened in a new location.  Instead of refreshing the cards, I see he list of previous locations with updated distance

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58345f0c1709f80100415b43/3fad447d-5a8a-4f3f-8336-19272816b0d1.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Nov 22 2016 21:41:01 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>14678.47</td></tr><tr><td>Build</td><td>358</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Maria's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>60% Unplugged</td></tr><tr><td>Memory free</td><td>34 MB / 1687 MB</td></tr><tr><td>Disk free</td><td>1238 MB / 11548 MB</td></tr><tr><td>Network IP</td><td>172.31.73.169</td></tr></table>

 [Link to buddybuild feedback from build 358](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5834bb6d7c18cc010066e054&bnum=358)

**Comment by fluffyemily** [comment] 2016-11-23 11:33
dupe of #225

**Closed by fluffyemily** 2016-11-23 11:33 UTC
Labels: 1.0, buddybuild-feedback
