### ISSUE TITLE
jmoradi@mozilla.com on build #407: Bug. This place opens at 7:30 am, not 6pm looks like parsing…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#298] opened 2016-11-25 16:22 UTC
Feedback from jmoradi@mozilla.com : Bug. This place opens at 7:30 am, not 6pm looks like parsing problem 

Also, I'm noticing that all the places around are given in walking time. I have a car but I guess work week folks will not. There are a lot of relevant breakfast  options to me (incl Hilton waikoloa that aren't showing 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/5837052f34ed490100aa6d47/f39ad2c3-aa03-4ebc-a09b-0752a7afb3c9.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Nov 25 2016 16:22:03 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>283.9062</td></tr><tr><td>Build</td><td>407</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>iPhone</td></tr><tr><td>Screen size</td><td>320</td></tr><tr><td>Screen size</td><td>320px by 568px</td></tr><tr><td>Battery</td><td>92% Unplugged</td></tr><tr><td>Memory free</td><td>42 MB / 1801 MB</td></tr><tr><td>Disk free</td><td>4123 MB / 56382 MB</td></tr><tr><td>Network IP</td><td>10.131.215.18</td></tr></table>

 [Link to buddybuild feedback from build 407](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5838652ba53efc0100808454&bnum=407)

**Comment by fluffyemily** [comment] 2016-11-28 10:09
dupe of #123

**Closed by fluffyemily** 2016-11-28 10:09 UTC
Labels: 1.0, buddybuild-feedback
