### ISSUE TITLE
rnewman@mozilla.com on build #655: Carousel animation occurs before the next image is fetched.…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#450] opened 2016-12-08 00:23 UTC
Feedback from rnewman@mozilla.com : Carousel animation occurs before the next image is fetched. Most noticeable on LTE, not wifi. 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58489480b7301301006dbd98/f6354f14-3613-473b-874f-d702f7edb7fd.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Thu Dec 08 2016 00:22:55 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>70.30438</td></tr><tr><td>Build</td><td>655</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Richard's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>56% Unplugged</td></tr><tr><td>Memory free</td><td>28 MB / 1764 MB</td></tr><tr><td>Disk free</td><td>12091 MB / 56428 MB</td></tr><tr><td>Network IP</td><td>10.136.197.138</td></tr></table>

 [Link to buddybuild feedback from build 655](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5848a7df0e597c0100c6ff8d&bnum=655)

**Comment by kbrosnan** [comment] 2016-12-08 19:38
Dupe of #414

**Closed by kbrosnan** 2016-12-08 19:38 UTC
Labels: 1.0, buddybuild-feedback
