### ISSUE TITLE
jmoradi@mozilla.com on build #472: Same bug: this place is actually open 11-2:30

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#311] opened 2016-11-26 21:03 UTC
Feedback from jmoradi@mozilla.com : Same bug: this place is actually open 11-2:30

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58388d882242fb010022a8ac/9dff0eff-3527-4999-bf3e-f8c83e9882bc.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Sat Nov 26 2016 21:03:37 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>713.7898</td></tr><tr><td>Build</td><td>472</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>iPhone</td></tr><tr><td>Screen size</td><td>320</td></tr><tr><td>Screen size</td><td>320px by 568px</td></tr><tr><td>Battery</td><td>49% Unplugged</td></tr><tr><td>Memory free</td><td>48 MB / 1673 MB</td></tr><tr><td>Disk free</td><td>3864 MB / 56382 MB</td></tr><tr><td>Network IP</td><td>10.74.79.33</td></tr></table>

 [Link to buddybuild feedback from build 472](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5839f8a9f189b10100f568f8&bnum=472)

**Comment by fluffyemily** [comment] 2016-11-28 10:09
dupe of #123

**Closed by fluffyemily** 2016-11-28 10:09 UTC
Labels: 1.0, buddybuild-feedback
