### ISSUE TITLE
alam@mozilla.com on build #529: Transparency in header

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#357] opened 2016-11-30 00:12 UTC
Feedback from alam@mozilla.com : Transparency in header

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/583dc8ca7017c20100bd23f4/b1c68c71-9eaa-48cc-b573-19aa7894c77c.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Nov 30 2016 00:12:01 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>813.5818</td></tr><tr><td>Build</td><td>529</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Antlam's 📱 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>72% Charging</td></tr><tr><td>Memory free</td><td>71 MB / 1515 MB</td></tr><tr><td>Disk free</td><td>74152 MB / 116301 MB</td></tr><tr><td>Network IP</td><td>0.0.0.0</td></tr></table>

 [Link to buddybuild feedback from build 529](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583e19519a5a8601009ca892&bnum=529)

**Comment by mcomella** [comment] 2016-11-30 15:40
* This was previously filed in #127 
* I made a speculative fix in #146
* I can't reproduce

@antlam Does this reproduce every time you run the app? In both "Prox" and "Prox Kona"?

**Comment by antlam** [comment] 2016-11-30 16:00
No, it's kind of random. 

I know we landed a speculative fix in #146 too but I guess this means it didn't work! so I just wanted to keep track of it.

Today's BB seemed to have fixed it :\

**Comment by sleroux** [comment] 2016-12-01 16:42
I also landed a speculative fix here: https://github.com/mozilla-mobile/prox/issues/277. I'll investigate. Happens randomly for me on my 6 as well.

**Comment by sleroux** [comment] 2016-12-01 18:58
Actual fix! https://github.com/mozilla-mobile/prox/pull/388

**Closed** 2016-12-02 14:58 UTC
Labels: 1.0, buddybuild-feedback, bug

**Comment by mcomella** [comment] 2017-01-11 21:38
![](https://github.trello.services/images/mini-trello-icon.png) [Transparency in header](https://trello.com/c/4fjNqZAb/286-transparency-in-header)
