### ISSUE TITLE
sarentz@mozilla.com on build #130: Blurry text on 6s Plus

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#70] opened 2016-10-31 12:37 UTC
Feedback from sarentz@mozilla.com : Blurry text on 6s Plus

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/581344efe76efc0100b136aa/4a7c434e-486f-427d-a43e-d2a6d8fa2709.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Mon Oct 31 2016 12:37:24 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>374.2202</td></tr><tr><td>Build</td><td>130</td></tr><tr><td>Device type</td><td>iPhone 6s Plus</td></tr><tr><td>Device name</td><td>Stefan's iPhone 6s Plus</td></tr><tr><td>Screen size</td><td>414</td></tr><tr><td>Screen size</td><td>414px by 736px</td></tr><tr><td>Battery</td><td>88% Unplugged</td></tr><tr><td>Memory free</td><td>53 MB / 1651 MB</td></tr><tr><td>Disk free</td><td>15767 MB / 116073 MB</td></tr><tr><td>Network IP</td><td>0.0.0.0</td></tr></table>

 [Link to buddybuild feedback from build 130](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=58173b044b3090010043e5ec&bnum=130)

**Comment by fluffyemily** [comment] 2016-10-31 16:12
Duplicate of https://github.com/mozilla-mobile/prox/issues/65

**Closed** 2016-10-31 16:13 UTC
Labels: 1.0, buddybuild-feedback, duplicate
