### ISSUE TITLE
mpopova@mozilla.com on build #553: No pictures showing up for the place

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#385] opened 2016-12-01 15:17 UTC
Feedback from mpopova@mozilla.com : No pictures showing up for the place

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/583f131b61760e0100964850/ac37f1e7-99c9-464f-9539-aa0ae4215178.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Thu Dec 01 2016 15:17:13 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>37.63069</td></tr><tr><td>Build</td><td>553</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Maria's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>100% Unplugged</td></tr><tr><td>Memory free</td><td>60 MB / 1710 MB</td></tr><tr><td>Disk free</td><td>1016 MB / 11548 MB</td></tr><tr><td>Network IP</td><td>10.5.161.80</td></tr></table>

 [Link to buddybuild feedback from build 553](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=58403ef9035c2501005010b5&bnum=553)

**Comment by fluffyemily** [comment] 2016-12-01 16:19
dupe of #217

**Closed by fluffyemily** 2016-12-01 16:19 UTC
Labels: 1.0, buddybuild-feedback
