### ISSUE TITLE
A radius of 0 in RemoteConfig can cause a crash loop

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/prox#265] opened 2016-11-23 23:17 UTC
The `search_radius_in_km` value was 0 from the RemoteConfig default values and it caused a crash loop in #261 where we crash on startup so we're unable to get new values in RemoteConfig and thus it resulted in a crash loop.

We should ensure this value (and the associated events value) is *never* 0 to prevent the crash loop.

Are there other values we should also verify to prevent crash loops?

**Comment by fluffyemily** [comment] 2016-11-24 10:39
dupe of #261

**Comment by mcomella** [comment] 2016-11-28 21:56
This isn't a dupe – this is defensive coding to prevent issues like #261.

To clarify, if the remote config searchRadiusInKm is ever set to 0, users will be stuck with a startup crash loop: since they crash on startup, they can never get the updated remote config values and they'll have to uninstall to fix it.

We should prevent this by verifying the radius value > 0 before we allow it to be set.

While we're at it, are there other values we should also verify to prevent crash loops?

**Comment by fluffyemily** [comment] 2016-11-29 10:52
Yes, radiusForCurrentLocationMonitoringMeters should also be defense checked

**Closed** 2016-12-01 17:28 UTC
