### ISSUE TITLE
mpopova@mozilla.com on build #358: List is much longer that 11 places, this badge is inaccurate…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#255] opened 2016-11-23 04:20 UTC
Feedback from mpopova@mozilla.com : List is much longer that 11 places, this badge is inaccurate 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58345f0c1709f80100415b43/76971298-6d90-473d-90a6-c266694a8206.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Nov 23 2016 04:20:25 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>23353.14</td></tr><tr><td>Build</td><td>358</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Maria's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>33% Unplugged</td></tr><tr><td>Memory free</td><td>56 MB / 1645 MB</td></tr><tr><td>Disk free</td><td>1243 MB / 11548 MB</td></tr><tr><td>Network IP</td><td>0.0.0.0</td></tr></table>

 [Link to buddybuild feedback from build 358](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=58351909c07ea0010089770d&bnum=358)

**Comment by fluffyemily** [comment] 2016-11-23 11:30
dupe of #198

**Closed by fluffyemily** 2016-11-23 11:30 UTC
Labels: 1.0, buddybuild-feedback
