### ISSUE TITLE
alam@mozilla.com on build #522: Swiping animation stutters and sometimes offsets vertically

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#339] opened 2016-11-29 17:33 UTC
Feedback from alam@mozilla.com : Swiping animation stutters and sometimes offsets vertically

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/583db82efac401010076c7da/deb6c802-0048-4573-83c4-8707523cc792.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Nov 29 2016 17:33:33 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>29.10924</td></tr><tr><td>Build</td><td>522</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Antlam's 📱 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>84% Unplugged</td></tr><tr><td>Memory free</td><td>68 MB / 1569 MB</td></tr><tr><td>Disk free</td><td>74272 MB / 116301 MB</td></tr><tr><td>Network IP</td><td>10.244.29.98</td></tr></table>

 [Link to buddybuild feedback from build 522](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583dbbed32832c01002af4c2&bnum=522)

**Comment by sleroux** [comment] 2016-11-29 17:49
Looks like the swipe delay is being caused by a force layout call here:

![screen shot 2016-11-29 at 12 45 22 pm](https://cloud.githubusercontent.com/assets/434322/20721697/c5d649f4-b631-11e6-82cb-da943245f48d.png)

Which was introduced in https://github.com/mozilla-mobile/prox/pull/325/commits/85a20291727cb322034b026d405edda8494d75e9. Usually using `setNeedsLayout` and letting the system perform it's layout pass can fix this but it looks like in this case we need the new layout calculations before we can properly update the coordinates in the CardView. I don't have much context on what's supposed to happen here but there might be a way to setup constraints in such a way that we won't need to do the manual calculation.

/cc @mcomella

**Comment by sleroux** [comment] 2016-11-29 20:12
Longer-than-normal stutter is resolved with https://github.com/mozilla-mobile/prox/pull/345.

The 'jump' is the same issue Kevin filed here: https://github.com/mozilla-mobile/prox/issues/201.

Since the first half is resolved and the second half has a dedicated bug I'm going to go ahead and close this.

**Closed by sleroux** 2016-11-29 20:12 UTC
Labels: 1.0, buddybuild-feedback
