### ISSUE TITLE
Unsatisfied Constraints

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/prox#242] opened 2016-11-22 14:32 UTC
From the console:
```
2016-11-22 14:28:33.766746 Prox[40651:3295835] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x610000291fd0 V:|-(16)-[UILabel:0x7f9c12566050]   (active, names: '|':Prox.PlaceDetailsEventView:0x7f9c12565bb0 )>",
    "<NSLayoutConstraint:0x6100002920c0 UILabel:0x7f9c12566050.bottom == Prox.PlaceDetailsEventView:0x7f9c12565bb0.bottom - 16   (active)>",
    "<NSLayoutConstraint:0x61800028d570 'UISV-hiding' Prox.PlaceDetailsEventView:0x7f9c12565bb0.height == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6100002920c0 UILabel:0x7f9c12566050.bottom == Prox.PlaceDetailsEventView:0x7f9c12565bb0.bottom - 16   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-11-22 14:28:33.774729 Prox[40651:3295835] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x618000287cb0 UIImageView:0x7f9c15040f00.height == 16   (active)>",
    "<NSLayoutConstraint:0x618000287d00 V:|-(20)-[UIImageView:0x7f9c15040f00]   (active, names: '|':Prox.HorizontalLineView:0x7f9c15045e30 )>",
    "<NSLayoutConstraint:0x618000287d50 UIImageView:0x7f9c15040f00.bottom == Prox.HorizontalLineView:0x7f9c15045e30.bottom   (active)>",
    "<NSLayoutConstraint:0x618000288160 UILabel:0x7f9c150462a0.height == 0   (active)>",
    "<NSLayoutConstraint:0x618000287990 V:|-(0)-[Prox.HorizontalLineView:0x7f9c15045e30]   (active, names: '|':Prox.PlaceDetailsDescriptionView:0x7f9c15001090 )>",
    "<NSLayoutConstraint:0x618000288070 V:[Prox.HorizontalLineView:0x7f9c15045e30]-(0)-[UILabel:0x7f9c150462a0]   (active)>",
    "<NSLayoutConstraint:0x6180002881b0 UILabel:0x7f9c150462a0.bottom == Prox.PlaceDetailsDescriptionView:0x7f9c15001090.bottom   (active)>",
    "<NSLayoutConstraint:0x61800028d750 'UISV-hiding' Prox.PlaceDetailsDescriptionView:0x7f9c15001090.height == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x618000287cb0 UIImageView:0x7f9c15040f00.height == 16   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-11-22 14:28:33.775619 Prox[40651:3295835] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x618000287d00 V:|-(20)-[UIImageView:0x7f9c15040f00]   (active, names: '|':Prox.HorizontalLineView:0x7f9c15045e30 )>",
    "<NSLayoutConstraint:0x618000287d50 UIImageView:0x7f9c15040f00.bottom == Prox.HorizontalLineView:0x7f9c15045e30.bottom   (active)>",
    "<NSLayoutConstraint:0x618000288160 UILabel:0x7f9c150462a0.height == 0   (active)>",
    "<NSLayoutConstraint:0x618000287990 V:|-(0)-[Prox.HorizontalLineView:0x7f9c15045e30]   (active, names: '|':Prox.PlaceDetailsDescriptionView:0x7f9c15001090 )>",
    "<NSLayoutConstraint:0x618000288070 V:[Prox.HorizontalLineView:0x7f9c15045e30]-(0)-[UILabel:0x7f9c150462a0]   (active)>",
    "<NSLayoutConstraint:0x6180002881b0 UILabel:0x7f9c150462a0.bottom == Prox.PlaceDetailsDescriptionView:0x7f9c15001090.bottom   (active)>",
    "<NSLayoutConstraint:0x61800028d750 'UISV-hiding' Prox.PlaceDetailsDescriptionView:0x7f9c15001090.height == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x618000287d50 UIImageView:0x7f9c15040f00.bottom == Prox.HorizontalLineView:0x7f9c15045e30.bottom   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
```

**Comment by fluffyemily** [comment] 2016-11-22 14:41
dupe of #190

**Comment by fluffyemily** [comment] 2016-11-29 12:36
This is still an issue. Product -> Edit Scheme -> Run -> Arguments and re-enable `OS_ACTIVITY_MODE` and you will see the constraint errors. I didn't realise that getting rid of the guff of logging would also suppress UIViewAlertForUnsatisfiableConstraints errors

**Closed** 2016-11-29 12:37 UTC
Labels: bug
