### ISSUE TITLE
UX - Place loading screen

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/prox#23] opened 2016-10-19 15:48 UTC
After the user has opened the app and we have requested places, we need to display something until we have a result. What should we display at this point.

Also to consider - we have previously found places, but we have now moved to a new location. How should we indicate that we are looking for new places?

**Comment by antlam** [comment] 2016-10-20 17:05
Looping in @vazquez to think about this some more. I've seen some of his ideas for loading/please wait screens that fits in well here I think.

**Comment by mcomella** [comment] 2016-10-20 18:09
@antlam A few more questions:
* What happens if 0 locations are found around the user?
* What happens if the current location is the only location found?
* What happens if the current location is not found?

**Comment by vazquez** [comment] 2016-10-20 18:18
While we are looking for new places, this is something we could show:

![loading](https://cloud.githubusercontent.com/assets/1119821/19572404/22d8c34c-96d0-11e6-81bf-1be03f400774.gif)

**Comment by vazquez** [comment] 2016-10-20 18:22
@mcomella –

 - What happens if 0 locations are found around the user?
  - I think we need to design a screen for this use-case, I'll create a GH issue.

- What happens if the current location is the only location found?
  - At least for MVP we would do just that, show the one location found. If we have time it would be nice to have a "Retry" button.

- What happens if the current location is not found?
  - Totally valid, I will create a GH issue for this.

**Comment by mcomella** [comment] 2016-10-20 21:30
> If we have time it would be nice to have a "Retry" button.

fwiw, seems pretty trivial to add on the engineering front.

Note to self: we'd just have to call `requestLocation` because we display new places in response to location updates.

**Comment by antlam** [comment] 2016-10-21 15:04
Quick note, we're currently pulling together a full list of these error states from the UX side.

**Comment by antlam** [comment] 2016-11-09 23:30
Seems to be a dupe of issue #131? 

I'll leave for @vazquez to close if it is

**Closed** 2016-11-10 01:53 UTC
Labels: question, UX
