### ISSUE TITLE
abenson@mozilla.com on build #655: Wondering if the background should not scroll with the card.…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#458] opened 2016-12-08 19:26 UTC
Feedback from abenson@mozilla.com : Wondering if the background should not scroll with the card. There's a jump that occurs with the UI when you scroll down on a card and then scroll horizontally. 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58489480b7301301006dbd98/044df9cf-6ad2-473e-9061-14edd15160e4.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Thu Dec 08 2016 19:26:36 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>288.4646</td></tr><tr><td>Build</td><td>655</td></tr><tr><td>Device type</td><td>iPhone 6s Plus</td></tr><tr><td>Device name</td><td>Aaron's iPhone</td></tr><tr><td>Screen size</td><td>414</td></tr><tr><td>Screen size</td><td>414px by 736px</td></tr><tr><td>Battery</td><td>40% Unplugged</td></tr><tr><td>Memory free</td><td>66 MB / 1484 MB</td></tr><tr><td>Disk free</td><td>8775 MB / 56233 MB</td></tr><tr><td>Network IP</td><td>172.16.150.78</td></tr></table>

 [Link to buddybuild feedback from build 655](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5849b3ec36e73d0100d532ea&bnum=655)

**Comment by kbrosnan** [comment] 2016-12-08 19:39
Dupe of #201

**Closed by kbrosnan** 2016-12-08 19:39 UTC
Labels: 1.0, buddybuild-feedback
